### ISSUE TITLE
Pull program from sale or make it donationware

### ISSUE THREAD

**Issue by TheSystemGuy1337** [nimaid/binary-waterfall#10]
Look, we have a problem. Pre-compiled versions are not freeware; however, its source code is **PUBLICLY AVAILABLE** on a GitHub repo (which is this one) which undermines your ability to even sell it as now crackers can just crack the software themselves or release a keygen. Unless you have obfuscated the activation code or implemented anti-consumer DRM, there is no way of stopping this. So, what's the point in selling it when people are just going to leverage the fact you put the source code up to crack your software? I see only two ways of going forward:

1. Pull the software from sale, or make the program _donationware_ (this is the best option)
2. Retract the programs source code and make it proprietary commercial software (and then worry about Razor 1911)

I suggest you make it donationware. Under a donationware license model, you still get paid for the software and you won't have to worry about piracy - this defeats the point of watermarks and license keys as now they are no longer necessary.

**Comment by nilgamingyt** [comment]
The worst part? The watermark is just a file.

**Comment by nimaid** [comment]
Are you suggesting that I make the .exe file a paid download outright? Just trying to understand.

FYI for the community: If you didn't already know, installing the program with `pip install binary-waterfall` gives you the full program without any watermark.

**Comment by nimaid** [comment]
@TheSystemGuy1337 Are you suggesting that I make the .exe file a paid download outright? Just trying to understand.

FYI for the community: If you didn't already know, installing the program with `pip install binary-waterfall` gives you the full program without any watermark.

**Comment by nimaid** [comment]
For the record, I like that idea a lot. The currently licensing system was designed to be as insecure as possible, because it was open source, so my thinking was "Why even try to make it hard for a technical user to crack it? Just let them." But forcing the user to go through a page that asks for a "$0 or more" donation would be ideal for this type of software.

Can anyone recommend a website that lets open-source creators upload for free and supports these sorts of optionally-paid downloads? I would happily remove all watermarks and licensing features instantly if I knew where to upload the .exe files.

**Comment by nimaid** [comment]
I just remembered that itch.io does this! I just released v3.7.0, which is completely free of any licensing or watermarks! The windows download icon now takes you the the itch.io page, where an optional donation is requested.

Anyone who bought a serial key should be automatically refunded, let me know if you have any issues. Thank you for supporting the project!

Stay tuned for a massive makeover for v4.0.0 as I move to a Qt Designer based layout, which will support window resizing, among other improvements.

**Comment by TheSystemGuy1337** [comment]
> @TheSystemGuy1337 Are you suggesting that I make the .exe file a paid download outright? As in to download it you have to donate "$0 or more" through an external webpage? Just trying to understand.
> 
> FYI for the community: If you didn't already know, installing the program with `pip install binary-waterfall` gives you the full program without any watermark.

I knew this was going to be controversial. I will preface this by saying I don't mind if you sell the software. It's your code, do whatever the fuck you want with it. However, selling open-source software is silly and not practical at all, as people could just download the original source code, compile it, and not pay a dime. For the donationware part: Yes, you would want the precompiled version to be on a website that allows for "$0 or more". The about section should also say "This program is donationware. If you like the program, you are encouraged to donate or share the program. Donation is optional."

But since you are changing over to a donationware model, would you like me to see if I could improve the about box?

**Comment by nimaid** [comment]
@TheSystemGuy1337 Sure, if you have some ideas for improvement I'll happily look over any pull requests you make. :)

**Comment by TheSystemGuy1337** [comment]
> @TheSystemGuy1337 Sure, if you have some ideas for improvement I'll happily look over any pull requests you make. :)

If there's an about box, we should add this line:

This software is donationware. If you like it, please donate to help fund development. Donation is optional.

**Comment by OsakaPhysics** [comment]
WHOEVER SAID THAT WITH THE PIP COMMAND. 
I OWE MY LIFE TO YOU
