### ISSUE TITLE
smartscreen

### ISSUE THREAD

**Issue by nilgamingyt** [nimaid/binary-waterfall#11]
Windows does not seem to like this program for some reason. It says it's going to put my PC at risk.
![Screenshot 2024-02-03 143005](https://github.com/nimaid/binary-waterfall/assets/96489682/273c3e9b-27e5-420e-9ae6-0d3f9741c336)

**Comment by nilgamingyt** [comment]
Quick update: This got flagged as a trojan by 2 security vendors on VirusTotal. I don't know why.
![image](https://github.com/nimaid/binary-waterfall/assets/96489682/65b4f266-6ba1-4312-9694-d8b43aa36fbe)

**Comment by Slimegodthethorn** [comment]
BECAUSE IT IS A HIGH POSSIBILITY OF A TROJAN!
DID YOU OPEN THE PROGRAM???
IF SO, YOU ARE INFECTED WITH WACATAC TROJAN!

**Comment by nilgamingyt** [comment]
genuinely shut the fuck up the program is literally open source how about you go check there

i might sound mean but if you want to really see if it has a virus go check the source code which I MIND YOU, IS ALREADY AVAILABLE. so dont call it a virus because you're being overly dramatic with VirusTotal.

**Comment by OsakaPhysics** [comment]
Wacatac is a False Positive due to PyInstaller, You can safely use this Program.
Pretty sure dude is trying to just make some shit up.

Have a nice day - Osaka
