### ISSUE TITLE
DO NOT OPEN OR DOWNLOAD

### ISSUE THREAD

**Issue by Slimegodthethorn** [nimaid/binary-waterfall#16]
Check https://www.virustotal.com/gui/file/b9a9d4b32be4a61fb9227e6af1d154de3677d77cafbffbe99bc250930a1048b9/detection

THIS FILE CONTAINS Trojan\Win32.Wacatac
BE CARFULL OF WHAT YOU DOWNLOAD

**Comment by nilgamingyt** [comment]
https://github.com/nimaid/binary-waterfall/assets/96489682/3c00e464-8505-4351-bb98-19b9022b80f1

Here's the raw data of a screenshot of this annoying complaint about a false positive, in Binary Waterfall.

**Comment by nimaid** [comment]
> Check https://www.virustotal.com/gui/file/b9a9d4b32be4a61fb9227e6af1d154de3677d77cafbffbe99bc250930a1048b9/detection
> 
> THIS FILE CONTAINS Trojan\Win32.Wacatac
> BE CARFULL OF WHAT YOU DOWNLOAD

Yes, this is a known false positive for a couple obscure antiviruses. It was likely flagged due to heuristic or AI analysis misinterpreting the code as malicious for some reason.

I have no idea how to fix this, but you can see at that link that all major antivirus software says this is clean.

Closing this issue due to it being a false positive. If you know how to fix this false positive detection, please open another issue.

**Comment by Slimegodthethorn** [comment]
My mistake, I'm really careful of malicious software, thanks for reporting that it's a false positive.
Sorry for the confusion
This was never meant be annoying fyi. Just a confusion.

**Comment by trillwin** [comment]
@Slimegodthethorn 

Binary waterfall is very malicious, uninstall it immediately

**Comment by bikethatreportsbugs36** [comment]
@trillwin no, and it a false postitive so try it urself

**Comment by trillwin** [comment]
> [@trillwin](https://github.com/trillwin) no, and it a false postitive so try it urself

i know that it is malicious i wont try it

**Comment by Slimegodthethorn** [comment]
My 2 year ago self complaining about something stupid. 
ItS mAlIcIoUs aAAaaAaaaA
What was I thinking back then?! LOL

**Comment by trillwin** [comment]
i dont trust whoever says its a false positive, not even a little

**Comment by girard05** [comment]
wait the windows fix new update to defender fix delete this viruse and fixxed

**Comment by girard05** [comment]
<img width="1223" height="304" alt="Image" src="https://github.com/user-attachments/assets/4c567414-ed9d-4c46-a1f0-94979677b05e" />

**Comment by trillwin** [comment]
@girard05 couldnt understand a single thing you said
