### ISSUE TITLE
Does Binary Waterfall support both 32-bit and 64-bit or only 64-bit

### ISSUE THREAD

**Issue by imthehappy** [nimaid/binary-waterfall#17]
I was wondering if binary waterfall supports both 32-bit and 64-bit or only 64-bit
I have Windows 8.1 32-bit
So can you tell me

**Comment by nimaid** [comment]
I have compiled it for 64-bits, so the `.exe` only runs on 64-bit CPUs.

You can however get the program on any platform through Python. Simply install Python 3, then run the command `pip3 install binary-waterfall`. You won't get any shortcuts for it, but if you run the command `binary-waterfall` it will open. You can make shortcuts for that command on your desktop and start menu if you want.
