### ISSUE TITLE
No mobile

### ISSUE THREAD

**Issue by Tailstuff** [nimaid/binary-waterfall#18]
I want to see what roms like .nes .z64 etc and other exes look like but I’m only on iPad can there be some mobile or web version of this because it’s really cool

**Comment by nimaid** [comment]
Well, the program IS written in Python. Most platforms run Python with a special app. It also uses the Qt5 framework for the GUI, which probably won't run on web or mobile.

Basically, I don't have any plans to make a mobile or web version. Honestly, for that, it would be better to completely rewrite the program in a different programming language. I'll leave that for someone else to do though, sorry.

If anyone does want to remake this, I would recommend using Javascript and HTML5. That would let it run in a browser, and making it into an app would be as easy as making a single-page offline web browser.
