### ISSUE TITLE
No such file or directory error when trying to use binary waterfall

### ISSUE THREAD

**Issue by 2ye3** [nimaid/binary-waterfall#3]
I don't have much info, but i'm going to show what happened in the CMD prompt.
_C:\Users\sunny>python binary-waterfall.py -h
python: can't open file 'C:\\Users\\censoreduser\\binary-waterfall.py': [Errno 2] No such file or directory_
I already opened the app and i _think_ it installed it? i'm not exactly sure.

**Comment by nimaid** [comment]
Hello,
You were using the old version of the program which required a working knowledge of command-line arguments. The newest version has a full GUI, meaning you can just run it like you tried and it will work.

Download the latest `.exe` file here: https://github.com/nimaid/binary-waterfall/releases/latest
